<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Try/catch Callbacks in Javascript - Will Haley</title>

  <meta name="author" content="will">
  <meta name="description" content="I came across an interesting issue with a node module recently. A callback was being invoked twice. Once on a success condition, and a second time as an error c...">

  <link rel="stylesheet" href="/css/main.css?version=1.1.6">
  <link rel="stylesheet" href="/css/custom.css?version=1.1.6">
  <link rel="canonical" href="http://willhaley.com/blog/try-catch-callbacks-in-javascript/">

  
  <link rel="manifest" href="/manifest.json?version=1.1.6">

  <link rel="shortcut icon" href="/favicon.ico?version=1.1.6">
  <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png?version=1.1.6">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png?version=1.1.6">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png?version=1.1.6">
  <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg?version=1.1.6">
  <meta name="msapplication-config" content="/browserconfig.xml?version=1.1.6">
  <meta name="theme-color" content="#ffffff">
</head>

<body>
  <header class="site-header" role="banner">
    <div class="wrapper" id="app">

      <a class="site-title" href="/">Will Haley</a>

      <nav class="site-nav">
        <input type="checkbox" id="nav-trigger" class="nav-trigger">
        <label for="nav-trigger">
          <span class="menu-icon">
            <svg viewBox="0 0 18 15" width="18px" height="15px">
              <path fill="#424242" d="M18,1.484c0,0.82-0.665,1.484-1.484,1.484H1.484C0.665,2.969,0,2.304,0,1.484l0,0C0,0.665,0.665,0,1.484,0 h15.031C17.335,0,18,0.665,18,1.484L18,1.484z"></path>
              <path fill="#424242" d="M18,7.516C18,8.335,17.335,9,16.516,9H1.484C0.665,9,0,8.335,0,7.516l0,0c0-0.82,0.665-1.484,1.484-1.484 h15.031C17.335,6.031,18,6.696,18,7.516L18,7.516z"></path>
              <path fill="#424242" d="M18,13.516C18,14.335,17.335,15,16.516,15H1.484C0.665,15,0,14.335,0,13.516l0,0 c0-0.82,0.665-1.484,1.484-1.484h15.031C17.335,12.031,18,12.696,18,13.516L18,13.516z"></path>
            </svg>
          </span>
        </label>

        <div class="trigger">
          <a class="page-link" href="/about/">About</a>
          <a class="page-link" href="/clippings/">Clippings</a>
          <a class="page-link" href="/favorites/">Favorites</a>
          <a class="page-link" href="/cv/">CV</a>
        </div>
      </nav>
    </div>
  </header>

  <main class="page-content" aria-label="Content">
    <div class="wrapper">
      
<article class="post" itemscope itemtype="http://schema.org/BlogPosting">
  <header class="post-header">
    <h1 class="post-title" itemprop="name headline">Try/catch Callbacks in Javascript</h1>
    <p class="post-meta"><time datetime="2015-05-08T19:46:12+00:00" itemprop="datePublished">May 8, 2015</time></p>
  </header>

  <h2 class="outdated">This article was last edited over 3 years ago. Information here may no longer be accurate. Please proceed with caution, and feel free to <a href="https://twitter.com/messages/compose?recipient_id=142425885&amp;text=Regarding%20article%20http%3a%2f%2fwillhaley.com%2fblog%2ftry-catch-callbacks-in-javascript%2f%0a%0a">contact me</a>.</h2><div class="post-content" itemprop="articleBody">
    <p>I came across an interesting issue with a node module recently. A callback was being invoked twice. Once on a success condition, and a second time as an error condition. We typically expect a callback to be invoked once. Either on success, or error, and not twice.</p>

<p>In hindsight, it was all my fault why I was encountering the issue, but a pattern in the third-party code really made it hard to debug.</p>

<!-- more -->

<p>Imagine I have some application code like this.</p>

<pre><code>function someFunction() {
  var timesCallbackInvoked = 0;

  someModule.someAsyncFunction(callback);

  function callback(err, response) {
    timesCallbackInvoked++;

    console.log('callback invoked: %s', timesCallbackInvoked);

    // Simulate a run time error.
    doSomethingStupid.INVALID_KEY;
  }
}
</code></pre>

<p>And the third-party code looks something like this.</p>

<pre><code>var someModule = {
  someAsyncFunction: function (callback) {
    try {
      // Do something.
      callback();
      return;
    } catch(exception) {
      // Do something with err.
      callback();
      return;
    }
  }
};
</code></pre>

<p>Then I call my function, which in turn calls the third-party function.</p>

<pre><code>someFunction();
</code></pre>

<p>What happens?  Well, we get a <code>ReferenceError</code>, because I&rsquo;m simulating a dumb run-time error in my code with <code>doSomethingStupid.INVALID_KEY</code>. And yes, that run-time error (simulated or not) is totally my fault and not the fault of the third-party module, but something very interesting happens because of how the third-party module is written.</p>

<pre><code>$ callback invoked: 1
$ callback invoked: 2
</code></pre>

<p>This happens because this third-party node module is invoking the callback in a <code>try</code> block.</p>

<pre><code>try {
  // If an exception is thrown either directly in
  // this `try` block, or down the call stack of
  // `callback`, we'll trigger `catch`.
  callback();
  return;
} catch(exception) {
  // This will catch errors not just within `try`,
  // but down the call stack of the `callback`
  // if it's executed in `try`. Oops!
  callback();
  return;
}
</code></pre>

<p>So if any exceptions are thrown down that call stack, the <code>catch</code> block will trigger. Since both the <code>try</code> block and the <code>catch</code> block invoke the callback, any exceptions in <code>callback</code> will result in the callback being invoked <em>twice</em>.</p>

<p>Here is how I would change that third-party code.</p>

<pre><code>var someModule = {
  someAsyncFunction: function (callback) {
    try {
      // Do something.
    } catch(exception) {
      // Do something with err.
    }
    callback();
    return;
  }
};
</code></pre>

<p>This time around, an exception will only result in the callback being invoked once, as we would expect.</p>

<pre><code>someFunction();
$ callback invoked: 1
</code></pre>

<p>This gives us the same functionality, but ensures that the callback will only be invoked once. Either in the success case, or the error case. Not potentially both.</p>

<p>A simple change, but a good lesson learned. Be very careful with your error handling and when and where you may invoke a callback. The nature of how the <code>try</code>/<code>catch</code> block wraps callers can lead to this sort of confusion otherwise.</p>

  </div>

  <div class="feedback">Feel free to <a target="_blank" href="https://twitter.com/messages/compose?recipient_id=142425885&amp;text=Regarding%20article%20http%3a%2f%2fwillhaley.com%2fblog%2ftry-catch-callbacks-in-javascript%2f%0a%0a">contact me</a> with questions or feedback regarding this article.</div>
  
</article>

    </div>
  </main>

  <footer class="site-footer">
    <div class="wrapper">
      <h2 class="footer-heading">Will Haley</h2>

      <div class="footer-col-wrapper">
        <div class="footer-col footer-col-1">
          <ul class="contact-list">
            <li>Will Haley</li>
            <li><a href="mailto:"></a></li>
          </ul>
        </div>

        <div class="footer-col footer-col-2">
          <ul class="social-media-list">

            <li>
              <a href="https://github.com/williamhaley"><span class="icon icon--github"><svg viewBox="0 0 16 16" width="16px" height="16px"><path fill="#828282" d="M7.999,0.431c-4.285,0-7.76,3.474-7.76,7.761 c0,3.428,2.223,6.337,5.307,7.363c0.388,0.071,0.53-0.168,0.53-0.374c0-0.184-0.007-0.672-0.01-1.32 c-2.159,0.469-2.614-1.04-2.614-1.04c-0.353-0.896-0.862-1.135-0.862-1.135c-0.705-0.481,0.053-0.472,0.053-0.472 c0.779,0.055,1.189,0.8,1.189,0.8c0.692,1.186,1.816,0.843,2.258,0.645c0.071-0.502,0.271-0.843,0.493-1.037 C4.86,11.425,3.049,10.76,3.049,7.786c0-0.847,0.302-1.54,0.799-2.082C3.768,5.507,3.501,4.718,3.924,3.65 c0,0,0.652-0.209,2.134,0.796C6.677,4.273,7.34,4.187,8,4.184c0.659,0.003,1.323,0.089,1.943,0.261 c1.482-1.004,2.132-0.796,2.132-0.796c0.423,1.068,0.157,1.857,0.077,2.054c0.497,0.542,0.798,1.235,0.798,2.082 c0,2.981-1.814,3.637-3.543,3.829c0.279,0.24,0.527,0.713,0.527,1.437c0,1.037-0.01,1.874-0.01,2.129 c0,0.208,0.14,0.449,0.534,0.373c3.081-1.028,5.302-3.935,5.302-7.362C15.76,3.906,12.285,0.431,7.999,0.431z"/></svg>
  </span><span class="username">williamhaley</span></a>
            </li>
          </ul>
        </div>

        <div class="footer-col footer-col-3">
          <p></p>
        </div>
      </div>
    </div>
  </footer>

  
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	ga('create', 'UA-16792239-1', 'auto');
	
	ga('send', 'pageview');
}
</script>


  <script src="/js/custom.js?version=1.1.6"></script>
</body>
</html>